package com.github.sarahbuisson.pitest.kotlin.extention.interceptor;

import org.pitest.mutationtest.build.InterceptorParameters;
import org.pitest.mutationtest.build.MutationInterceptor;
import org.pitest.mutationtest.build.MutationInterceptorFactory;
import org.pitest.mutationtest.tooling.SmartSourceLocator;
import org.pitest.plugin.Feature;

public class KotlinDataInterceptorFactory implements
        MutationInterceptorFactory {

    @Override
    public String description() {
        return "disable the mutation coverage for the line generated by the data kotlin word";
    }

    @Override
    public Feature provides() {
        return Feature.named("Kotlin_FileFilter")
                .withOnByDefault(true)
                .withDescription(description());

    }

    @Override
    public MutationInterceptor createInterceptor(InterceptorParameters params) {
        return new KotlinDataInterceptor(new SmartSourceLocator(params.data().getSourceDirs()), params.data(), params.source());

    }
}
