package org.sbuisson.pitest.extention.kotlin.intercept;

import org.pitest.classinfo.ClassByteArraySource;
import org.pitest.mutationtest.build.InterceptorParameters;
import org.pitest.mutationtest.build.MutationInterceptor;
import org.pitest.mutationtest.build.MutationInterceptorFactory;
import org.pitest.mutationtest.config.ReportOptions;
import org.pitest.plugin.Feature;

public class KotlinDataInterceptorFactory implements
        MutationInterceptorFactory {

  public String description() {
    return "disable the mutation coverage for the line generated by the data kotlin word";
  }


  public Feature provides() {
    return Feature.named("Kotlin_FileFilter")
            .withOnByDefault(true)
            .withDescription(description());

  }

  public MutationInterceptor createInterceptor(InterceptorParameters interceptorParameters) {
    return new KotlinDataInterceptor(interceptorParameters);
  }
}
