package org.sbuisson.pitest.extention.kotlin.intercept;

import org.pitest.classinfo.ClassByteArraySource;
import org.pitest.mutationtest.build.MutationInterceptor;
import org.pitest.mutationtest.build.MutationInterceptorFactory;
import org.pitest.mutationtest.config.ReportOptions;

public class KotlinDataInterceptorFactory implements
        MutationInterceptorFactory {

  public String description() {
    return "disable the mutation coverage for the line generated by the data kotlin word";
  }


  public MutationInterceptor createInterceptor(ReportOptions data, ClassByteArraySource source) {
    return new KotlinDataInterceptor( data, source);
  }
}
